### ISSUE TITLE
Cannot retrieve addresses from Polkadot Ledgeracio app

### ISSUE THREAD

**Issue by Demi-Marie** [Zondax/ledger-kusama-rs#10]
I cannot retrieve addresses from the Polkadot Ledgeracio app.  The Kusama app works fine, and I have checked that my derivation paths are correct.

**Comment by jleni** [comment]
Are you sure you are using the correct derivation path?
Polkadot starts with 44'/354' ... 
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by jleni** [comment]
otherwise, could you provide more information in the issue?

**Comment by Demi-Marie** [comment]
Bug is [the makefile’s setting of APPPATH](https://github.com/Zondax/ledger-polkadot/blob/b3726e6a7db8b4f8e13c408daf3cb9a32f3bf71e/app/Makefile#L38-L43): it is set to the Kusama value, not the Polkadot one.

I will make a PR.
