### ISSUE TITLE
Tests fail with APDU_CODE_CLA_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Demi-Marie** [Zondax/ledger-kusama-rs#3]
I get `Error: Ledger(Apdu("[APDU_CODE_CLA_NOT_SUPPORTED] Class not supported"))` when running tests.

**Comment by jleni** [comment]
@DemiMarie-parity  I think this should be working well in the dev branch, correcT?

**Comment by Demi-Marie** [comment]
@jleni Indeed it was last I checked.  If it breaks again, that is a different bug.  Closing.
