### ISSUE TITLE
Document the `cla` parameter to SubstrateApp::new

### ISSUE THREAD

**Issue by Demi-Marie** [Zondax/ledger-kusama-rs#9]
Ledgeracio works if I pass 0, but there should be some documentation.

**Comment by jleni** [comment]
mm.. maybe I should make that constructor private.

In practice, you should be calling these functions:

https://github.com/Zondax/ledger-substrate-rs/blob/c5520a6348d1b58141440f0f5e99125a4dda97ce/src/lib.rs#L48-L61
